### PR TITLE
Build: support minimal link flags

### PR DESCRIPTION
**Pull request by yihuang**
~~Removing these flags seems have no side effects, but make life easier with my package manager (nix), where I only need to install librocksdb, rather than installing all the indirect dependencies, those are indirectly brought in anyway.~~

In many cases, we don't need the extra link flags, either because librocksdb already referenced the indirect dependencies by path, or it's not built with it at all, so this PR introduce a build tag `grocksdb_clean_link` to only link minimal dependencies.

### CODE REVIEW

**Comment by linxGnu** [comment]
Hello @yihuang , I am afraid of many current builds does not contains linking to lz4, snappy. Removing links might break those systems.

**Comment by yihuang** [comment]
> Hello @yihuang , I am afraid of many current builds does not contains linking to lz4, snappy. Removing links might break those systems.

are those libs are built with librocksdb itself? if librocksdb is not built with them, it doesn't matter if we specify them here?

**Comment by yihuang** [comment]
> @yihuang yes, fyi, they are custom builds. There are many custom-builds like this.

I mean if the librocksdb is built with them, it doesn't matter if we specify here or not, do you get a link error if we don't specify the flags here?

**Comment by yihuang** [comment]
Did you do static link?

**Comment by yihuang** [comment]
@linxGnu how about make it optional, I added a build tag `grocksdb_clean_link`, so the default behavior is not changed.

**Comment by linxGnu** [comment]
Sound great to me when using directive building. Let me have a look this week and feedback to you on Monday. Thank you for the contribution

**Review by linxGnu — APPROVED** [review]

**Pull request merged**
