### PR TITLE
Add Native method to return C native

### PR DESCRIPTION
**Pull request by muthukrishnan24**
This PR adds Native methods to return unsafe.Pointer of native C

### CODE REVIEW

**Comment by muthukrishnan24** [comment]
@linxGnu can you please review this PR?

**Comment by linxGnu** [comment]
@muthukrishnan24 Hi, I am sorry for late reply. It was holiday in Japan. 

Could you please describe the use-case why we need to expose unsafe pointer?

**Comment by muthukrishnan24** [comment]
The idea is get access to C structs which can be passed to c functions.
since C.structs are unexported, only way is to return unsafe.Pointer and typecast them.

**Comment by linxGnu** [comment]
@muthukrishnan24 could you please resolve the conflict before we continue. Thank you

**Pull request closed without merging**
