### PR TITLE
don't build `rocksdb_property_int`/`rocksdb_property_int_cf` on windows

### PR DESCRIPTION
**Pull request by yihuang**
they are not exported by rocksdb on windows in current version.
see: https://github.com/facebook/rocksdb/pull/11217

### CODE REVIEW

**Comment by linxGnu** [comment]
@yihuang I think it's better to make it directive. If os != window -> having this function.

**Comment by yihuang** [comment]
> @yihuang I think it's better to make it directive. If os != window -> having this function.

sounds good

**Comment by yihuang** [comment]
done

**Comment by linxGnu** [comment]
@yihuang imho, the test also need to be directive

**Comment by yihuang** [comment]
> @yihuang imho, the test also need to be directive

done

**Review by linxGnu — APPROVED** [review]
LGTM. Thank you very much @yihuang

**Pull request merged**
